name: Qodana Test

on:
  push:
    branches: [ "main" ]

jobs:
  analyze-qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: read # privateリポジトリでは必要（無いときの挙動は試してないがそもそもコードのチェックアウトで必要）
    steps:
      - uses: actions/checkout@v4
        # with:
        #   # ref: ${{ github.event.pull_request.head.sha }} # どのコードを解析するか。プルリクではheadでなくマージコミットでもよいと思う
        #   # fetch-depth: 0  # pr-mode のときに必要（0でない場合はエラーにはならないがプルリクでも全ファイル検査となる）
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        # env:
        #   QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # Qodanaのダッシュボードと連携する場合
        with:
          use-annotations: false
