name: Sarif CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze-codeql:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        #language: [ 'java-kotlin', 'swift' ]
        language: [ 'java-kotlin' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      #- run: ./gradlew assembleDebug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          #category: "/language:${{matrix.language}}"
          category: "codeql:${{matrix.language}}"

      - uses: actions/upload-artifact@v3
        with:
          path: /home/runner/work/iosched/results
#          #path: /home/runner/work/sarif-android-sample/results/java.sarif
